#!/usr/bin/python3
"""find these two primes p and q of given n, n = p x q"""
import sys
import math

with open(sys.argv[1], "r") as fp:
    n = int(fp.readline())
    # check if value is even
    if n % 2 == 0:
        print("{}={}*{}".format(n, int(n / 2), 2))
    # value is odd number
    else:
        a = int(math.sqrt(n)) + 1
        b2 = int(a * a - n)
        b = int(math.sqrt(b2))
        while b ** 2 != int(b2):
            a += 1
            b2 = a * a - n
        print("{}={}*{}".format(n, int(a + math.sqrt(b2)),
                                int(a - math.sqrt(b2))))
